# generated by datamodel-codegen:
#   filename:  conversion-v1.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class Operation(StrEnum):
    inspect = 'inspect'
    configure = 'configure'
    prepare = 'prepare'
    verify = 'verify'


class Capability(StrEnum):
    core = 'core'
    vector = 'vector'
    raster = 'raster'
    multidim = 'multidim'
    pointcloud = 'pointcloud'


class Input(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: constr(min_length=1)
    filename: constr(min_length=1)
    sizeBytes: conint(ge=0, le=9007199254740991)
    mediaType: str | None


class EarthStoriesConversionProtocolV11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: Literal['earth-stories/conversion/v1']
    requestId: constr(min_length=1)
    projectId: constr(min_length=1)
    operation: Operation
    capability: Capability
    input: Input
    options: dict[str, Any]


class Stage(StrEnum):
    queued = 'queued'
    provisioning = 'provisioning'
    inspecting = 'inspecting'
    preparing = 'preparing'
    verifying = 'verifying'


class Unit(StrEnum):
    bytes = 'bytes'
    features = 'features'
    steps = 'steps'


class EarthStoriesConversionProtocolV12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: Literal['earth-stories/conversion/v1']
    requestId: constr(min_length=1)
    type: Literal['progress']
    stage: Stage
    completed: confloat(ge=0.0)
    total: PositiveFloat | None
    unit: Unit
    message: str


class Tool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    version: constr(min_length=1)


class EarthStoriesConversionProtocolV13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: Literal['earth-stories/conversion/v1']
    requestId: constr(min_length=1)
    type: Literal['result']
    status: Literal['succeeded']
    output: dict[str, Any]
    tools: list[Tool]
    warnings: list[str]


class Status(StrEnum):
    failed = 'failed'
    cancelled = 'cancelled'


class EarthStoriesConversionProtocolV14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: Literal['earth-stories/conversion/v1']
    requestId: constr(min_length=1)
    type: Literal['failure']
    status: Status
    code: constr(min_length=1)
    message: constr(min_length=1)
    retryable: bool
    details: dict[str, Any]


class EarthStoriesConversionProtocolV1(
    RootModel[
        EarthStoriesConversionProtocolV11
        | EarthStoriesConversionProtocolV12
        | EarthStoriesConversionProtocolV13
        | EarthStoriesConversionProtocolV14
    ]
):
    root: (
        EarthStoriesConversionProtocolV11
        | EarthStoriesConversionProtocolV12
        | EarthStoriesConversionProtocolV13
        | EarthStoriesConversionProtocolV14
    ) = Field(..., title='Earth Stories conversion protocol v1')
