export const productTokens = {
  fonts: {
    body: '"Satoshi Variable", "Satoshi", system-ui, sans-serif',
    mono: '"DM Mono", ui-monospace, monospace',
  },
  colors: {
    canvas: "#F5F3F0",
    subtle: "#FCFBF9",
    raised: "#FFFFFF",
    emphasized: "#EFEBE6",
    mutedSurface: "#E5E0DA",
    text: "#443F3F",
    textMuted: "#716B68",
    textPlaceholder: "#98918D",
    textDisabled: "#AAA39F",
    border: "#E8E5E0",
    borderEmphasized: "#CFC9C2",
    action: "#CF3F02",
    actionHover: "#B83800",
    focusSubtle: "rgba(207, 63, 2, 0.18)",
    selection: "#F7DED2",
    selectionSubtle: "rgba(207, 63, 2, 0.1)",
    overlay: "rgba(68, 63, 63, 0.34)",
    disabled: "rgba(68, 63, 63, 0.08)",
    mapChrome: "rgba(255, 255, 255, 0.94)",
    success: "#236637",
    successBg: "#EAF5ED",
    successBorder: "#B8DCC1",
    warning: "#79551A",
    warningBg: "#FFF4D8",
    warningBorder: "#E8CE91",
    danger: "#A12E0A",
    dangerBg: "#FFF0EA",
    dangerBorder: "#E4B59F",
    dangerHover: "#842306",
    info: "#315F75",
    infoBg: "#EAF4F8",
    infoBorder: "#B9D7E4",
  },
  radii: { control: "8px", panel: "12px" },
  shadows: {
    xs: "0 1px 2px rgba(68, 63, 63, 0.05)",
    sm: "0 2px 8px rgba(68, 63, 63, 0.07)",
    md: "0 10px 28px rgba(68, 63, 63, 0.1)",
    lg: "0 18px 48px rgba(68, 63, 63, 0.14)",
    panel: "-18px 0 48px rgba(68, 63, 63, 0.16)",
  },
  motion: {
    fast: "180ms",
    moderate: "240ms",
    slow: "340ms",
    easing: "cubic-bezier(0.32, 0.72, 0, 1)",
  },
  zIndex: {
    base: 0,
    sticky: 10,
    mapControl: 20,
    overlay: 30,
    modal: 100,
    toast: 200,
  },
  density: {
    compactControl: "32px",
    standardControl: "40px",
    comfortableControl: "44px",
    inspectorGap: "12px",
    sectionGap: "20px",
    editorRail: "240px",
    compactEditorRail: "200px",
  },
} as const;

export const productCssVariables = {
  "--es-font-body": productTokens.fonts.body,
  "--es-font-mono": productTokens.fonts.mono,
  "--es-bg": productTokens.colors.canvas,
  "--es-bg-subtle": productTokens.colors.subtle,
  "--es-bg-raised": productTokens.colors.raised,
  "--es-bg-emphasized": productTokens.colors.emphasized,
  "--es-bg-muted": productTokens.colors.mutedSurface,
  "--es-fg": productTokens.colors.text,
  "--es-fg-muted": productTokens.colors.textMuted,
  "--es-fg-placeholder": productTokens.colors.textPlaceholder,
  "--es-fg-disabled": productTokens.colors.textDisabled,
  "--es-border": productTokens.colors.border,
  "--es-border-emphasized": productTokens.colors.borderEmphasized,
  "--es-action": productTokens.colors.action,
  "--es-action-hover": productTokens.colors.actionHover,
  "--es-action-fg": productTokens.colors.raised,
  "--es-focus-subtle": productTokens.colors.focusSubtle,
  "--es-selection": productTokens.colors.selection,
  "--es-selection-subtle": productTokens.colors.selectionSubtle,
  "--es-overlay": productTokens.colors.overlay,
  "--es-disabled": productTokens.colors.disabled,
  "--es-map-chrome": productTokens.colors.mapChrome,
  "--es-success": productTokens.colors.success,
  "--es-success-bg": productTokens.colors.successBg,
  "--es-success-border": productTokens.colors.successBorder,
  "--es-warning": productTokens.colors.warning,
  "--es-warning-bg": productTokens.colors.warningBg,
  "--es-warning-border": productTokens.colors.warningBorder,
  "--es-danger": productTokens.colors.danger,
  "--es-danger-bg": productTokens.colors.dangerBg,
  "--es-danger-border": productTokens.colors.dangerBorder,
  "--es-info": productTokens.colors.info,
  "--es-info-bg": productTokens.colors.infoBg,
  "--es-info-border": productTokens.colors.infoBorder,
  "--es-radius-control": productTokens.radii.control,
  "--es-radius-panel": productTokens.radii.panel,
  "--es-shadow-xs": productTokens.shadows.xs,
  "--es-shadow-sm": productTokens.shadows.sm,
  "--es-shadow-md": productTokens.shadows.md,
  "--es-shadow-panel": productTokens.shadows.panel,
  "--es-transition": `${productTokens.motion.fast} ${productTokens.motion.easing}`,
  "--es-z-sticky": String(productTokens.zIndex.sticky),
  "--es-z-map-control": String(productTokens.zIndex.mapControl),
  "--es-z-overlay": String(productTokens.zIndex.overlay),
  "--es-z-modal": String(productTokens.zIndex.modal),
  "--es-z-toast": String(productTokens.zIndex.toast),
  "--es-control-compact": productTokens.density.compactControl,
  "--es-control-standard": productTokens.density.standardControl,
  "--es-control-comfortable": productTokens.density.comfortableControl,
  "--es-inspector-gap": productTokens.density.inspectorGap,
  "--es-section-gap": productTokens.density.sectionGap,
  "--es-editor-rail-width": productTokens.density.editorRail,
  "--es-editor-rail-width-compact": productTokens.density.compactEditorRail,
} as const;
